


 const  ElectronicsDatas=[
   {
       id: 1,
       image: "https://m.media-amazon.com/images/I/317IeU7IATL._AC_SX450_.jpg",
       imageTwo:"https://m.media-amazon.com/images/I/317IeU7IATL._AC_SX450_.jpg",
       imageThree:"https://m.media-amazon.com/images/I/218nnqhKXrL._AC_SX450_.jpg",
       imageFour:"https://m.media-amazon.com/images/I/41ugRZrc6WL._AC_SX450_.jpg",
       title: "LG UHD 4K TV 55 Inch UQ7500 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ - 55UQ75006L, Bluetooth, Wi-Fi, Ethernet, HDMI, NFC",
       starNum: 27,
       para: "200+ bought in past month",
       price: 19.999,
       del: 17.999,
       otherpara: "Get it as soon as tomorrow, 24 Mar",
      otherparapara: "Fulfilled by Amazon - FREE Shipping",
      inStock: true,
      rating:5,
      reviews: "69,548",
      listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
      listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
      listThree: "PLATFORM OS: Android 13, One UI 5.1",
      listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
      brandName:"Samsung",
      modelName:"Galaxy S24 Ultra",
      wirelessProvider:"Unlocked for All Carriers",
      OperatingSystem: "Android",
      cellular: "5G",
      memoryStorage:"256GB"
   }, 
 

   {
       id: 2,
       image: "https://m.media-amazon.com/images/I/61ERH+yIyiL._AC_UL320_.jpg",
       imageTwo:"	https://m.media-amazon.com/images/I/61UpnjTTo8L._AC_SX679_.jpg",
       imageThree:"https://m.media-amazon.com/images/I/41+dk8b4+OL._AC_SX679_.jpg",
       imageFour:"https://m.media-amazon.com/images/I/51QoWcfEdYL._AC_SX679_.jpg",
       title: "Samsung Galaxy A55 5G, Android Smartphone, Dual SIM Mobile Phone, 8GB RAM, 256GB Storage, Awesome Navy - 1 year Warranty",
       starNum: 7145,
       para: "200+ bought in past month",
       price:  18.999,
       del: 20.298,
       otherpara: "Get it as soon as tomorrow, 24 Mar",
      otherparapara: "Fulfilled by Amazon - FREE Shipping",
      inStock: true,
      rating:5,
      reviews: "69,548",
      brandName:"Nokia",
      modelName:"G21",
      wirelessProvider:"Unlocked for All Carriers",
      OperatingSystem: "Android",
      cellular: "5G",
      memoryStorage:"256GB"
   }, 


   {
       id: 3,
       image: "	https://m.media-amazon.com/images/I/61tIUqwUlCL._AC_UL320_.jpg",
       imageTwo:"https://m.media-amazon.com/images/I/61T2Npla2fL._AC_SX450_.jpg",
       imageThree:"https://m.media-amazon.com/images/I/61tIUqwUlCL._AC_UL320_.jpg",
       imageFour:"https://m.media-amazon.com/images/I/4184KvmMyqL._AC_SX450_.jpg",
       title: "Samsung 55 Inch TV Crystal Processor 4K LED with Built-in Receiver - Black - UA55CU8000UXEG [2023 Model]",
       starNum: 624,
       para: "200+ bought in past month",
       price: 529,
       del: 599,
       otherpara: "Get it as soon as tomorrow, 24 Mar",
      otherparapara: "Fulfilled by Amazon - FREE Shipping",
      inStock: false,
      rating:3,
      reviews: "69,548",
      brandName:"Samsung",
      modelName:"G21",
      wirelessProvider:"Unlocked for All Carriers",
      OperatingSystem: "Android",
      cellular: "5G",
      memoryStorage:"256GB"
   },    
      {
       id: 4,
       image:"	https://m.media-amazon.com/images/I/61AShXhK12L._AC_SX569_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51d51Ory2BL._AC_SX569_.jpg",
        imageTree:" https://m.media-amazon.com/images/I/71zVM-q9UFL._AC_SX569_.jpg",
        imageFour:"https://m.media-amazon.com/images/I/51ycyi6yCJL._AC_SX569_.jpg",

       title: "Honor Pad X9 11.5 Inches Space Gray 4GB RAM 128GB Wi-Fi TFT LCD (IPS) 7250 mAh with Flip Cover - Middle East Version",
       starNum: 74,
       para: "200+ bought in past month",
       price:7.888,
       otherpara: "Get it as soon as tomorrow, 24 Mar",
      otherparapara: "Fulfilled by Amazon - FREE Shipping",
      inStock: true,
      rating:4,
      reviews: "69,548",
      brandName:"Samsung",
      modelName:"G21",
      wirelessProvider:"Unlocked for All Carriers",
      OperatingSystem: "Android",
      cellular: "5G",
      memoryStorage:"256GB"
   },  
 
   {
      id: 5,
      image:"https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
       imageTwo:"https://m.media-amazon.com/images/I/51muL65bc7L._AC_SX569_.jpg",
       imageThree:"	https://m.media-amazon.com/images/I/71Lv32ogyOL._AC_SX569_.jpg",
       imageFour:"	https://m.media-amazon.com/images/I/61Sd85nQE2L._AC_SX569_.jpg",
      title: "Samsung Galaxy S23 FE 5G Dual SIM Android Smartphone, 8GB RAM, 256GB ROM - Cream",
      starNum: 74,
      para: "200+ bought in past month",
      price: 22.999,
      del: 23.900,
      otherpara: "Get it as soon as tomorrow, 24 Mar",
     otherparapara: "Fulfilled by Amazon - FREE Shipping",
     inStock: false,
     rating:5,
     reviews: "69,548",
     brandName:"Samsung",
     modelName:"G21",
     wirelessProvider:"Unlocked for All Carriers",
     OperatingSystem: "Android",
     cellular: "5G",
     memoryStorage:"256GB"
  }, 
     {
      id: 6,
      title:"Oraimo FreePods Lite True Wireless Earbuds Bluetooth TWS Earphone with APP Control,40h Play Time, Anifast Fast Charging,in-Ear Earbuds with Stereo",
    image:"https://m.media-amazon.com/images/I/61zbcOwRoPL._AC_UL320_.jpg",
    imageTwo:"	https://m.media-amazon.com/images/I/71CeV7CMkGL._AC_SY450_.jpg",
    imageThree:"	https://m.media-amazon.com/images/I/71b8sJNPZRL._AC_SY450_.jpg",
    imageFour:"https://m.media-amazon.com/images/I/71CeV7CMkGL._AC_SY450_.jpg",
      starNum: 74,
      para: "200+ bought in past month",
      price: 6.989,
      del: 15.315,
      otherpara: "Get it as soon as tomorrow, 24 Mar",
     otherparapara: "Fulfilled by Amazon - FREE Shipping",
     inStock: true,
     rating:5,
     reviews: "69,548",
     brandName:"Samsung",
     modelName:"G21",
     wirelessProvider:"Unlocked for All Carriers",
     OperatingSystem: "Android",
     cellular: "5G",
     memoryStorage:"256GB"
  },
  {
    id: 7,
    title:"Oraimo Watch 2R Bluetooth Calling Smart Watch for Men and Women,1.39 HD Smart Fitness Watch with Stepping Meter Heart Rate",
  image:"https://m.media-amazon.com/images/I/61shUuiQKiL._AC_UL320_.jpg",
  imageTwo:"	https://m.media-amazon.com/images/I/61FHscI4SAL._AC_SY450_.jpg",
  imageThree: "https://m.media-amazon.com/images/I/71xOGlDdD4L._AC_SY450_.jpg",
  imageFour:"https://m.media-amazon.com/images/I/71RzxAnoWjL._AC_SY450_.jpg",
    starNum: 74,
    para: "200+ bought in past month",
    price: 1.203,
    del: 1.300,
    otherpara: "Get it as soon as tomorrow, 24 Mar",
   otherparapara: "Fulfilled by Amazon - FREE Shipping",
   inStock: true,
   rating:5,
   reviews: "69,548",
   brandName:"Samsung",
   modelName:"G21",
   wirelessProvider:"Unlocked for All Carriers",
   OperatingSystem: "Android",
   cellular: "5G",
   memoryStorage:"256GB"
},
  {
   id: 8,
   image:"https://m.media-amazon.com/images/I/51OIq5aut4L._AC_UL320_.jpg",
    imageTwo:	"	https://m.media-amazon.com/images/I/41+j5ztXRvL._AC_SX569_.jpg",
    imageTree:" https://m.media-amazon.com/images/I/51OIq5aut4L._AC_UL320_.jpg",
    imageFour:"	https://m.media-amazon.com/images/I/51hhoCzQe4L._AC_SY879_.jpg ",
   title: "Samsung Galaxy Tab A9 LTE Android Tablet, 8GB RAM, 128GB Storage, Graphite",
   starNum: 74,
   para: "200+ bought in past month",
   price:90394,
   otherpara: "Get it as soon as tomorrow, 24 Mar",
  otherparapara: "Fulfilled by Amazon - FREE Shipping",
  inStock: true,
  rating:4,
  reviews: "69,548",
  brandName:"Samsung",
  modelName:"G21",
  wirelessProvider:"Unlocked for All Carriers",
  OperatingSystem: "Android",
  cellular: "5G",
  memoryStorage:"256GB"
},
{
   id: 9,
   image: "	https://m.media-amazon.com/images/I/51Azws7WRIL._AC_UL320_.jpg",
   imageTwo:"	https://m.media-amazon.com/images/I/51bIZppQi8L._AC_SX450_.jpg",
   imageThree:"	https://m.media-amazon.com/images/I/41xgtq09k-L._AC_SX450_.jpg",
   imageFour:"https://m.media-amazon.com/images/I/41q8FeHPjQL._AC_SX450_.jpg",
   title: "EZVIZ CS-TY1 1080p 360-Degree WiFi Smart Home Security Camera, Intelligent Surveillance Camera with Night Vision, Smart Tracking, Two-way",
   starNum: 7145,
   para: "200+ bought in past month",
   price:  1.029,
   del: 1.700,
   otherpara: "Get it as soon as tomorrow, 24 Mar",
  otherparapara: "Fulfilled by Amazon - FREE Shipping",
  inStock: true,
  rating:5,
  reviews: "69,548",
  brandName:"Nokia",
  modelName:"G21",
  wirelessProvider:"Unlocked for All Carriers",
  OperatingSystem: "Android",
  cellular: "5G",
  memoryStorage:"256GB"
}
]
export default ElectronicsDatas


