const  ElectronicsDatasThree=[

    {
           id: 5,
           image:"https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
            imageTwo:"https://m.media-amazon.com/images/I/51muL65bc7L._AC_SX569_.jpg",
            imageThree:"	https://m.media-amazon.com/images/I/71Lv32ogyOL._AC_SX569_.jpg",
            imageFour:"	https://m.media-amazon.com/images/I/61Sd85nQE2L._AC_SX569_.jpg",
           title: "Samsung Galaxy S23 FE 5G Dual SIM Android Smartphone, 8GB RAM, 256GB ROM - Cream",
           starNum: 74,
           para: "200+ bought in past month",
           price: 22.999,
           del: 23.900,
           otherpara: "Get it as soon as tomorrow, 24 Mar",
          otherparapara: "Fulfilled by Amazon - FREE Shipping",
          inStock: false,
          rating:5,
          reviews: "69,548",
          brandName:"Samsung",
          modelName:"G21",
          wirelessProvider:"Unlocked for All Carriers",
          OperatingSystem: "Android",
          cellular: "5G",
          memoryStorage:"256GB"
       }, 
          {
           id: 6,
           title:"Oraimo FreePods Lite True Wireless Earbuds Bluetooth TWS Earphone with APP Control,40h Play Time, Anifast Fast Charging,in-Ear Earbuds with Stereo",
         image:"https://m.media-amazon.com/images/I/61zbcOwRoPL._AC_UL320_.jpg",
         imageTwo:"	https://m.media-amazon.com/images/I/71CeV7CMkGL._AC_SY450_.jpg",
         imageThree:"	https://m.media-amazon.com/images/I/71b8sJNPZRL._AC_SY450_.jpg",
         imageFour:"https://m.media-amazon.com/images/I/71CeV7CMkGL._AC_SY450_.jpg",
           starNum: 74,
           para: "200+ bought in past month",
           price: 6.989,
           del: 15.315,
           otherpara: "Get it as soon as tomorrow, 24 Mar",
          otherparapara: "Fulfilled by Amazon - FREE Shipping",
          inStock: true,
          rating:5,
          reviews: "69,548",
          brandName:"Samsung",
          modelName:"G21",
          wirelessProvider:"Unlocked for All Carriers",
          OperatingSystem: "Android",
          cellular: "5G",
          memoryStorage:"256GB"
       },
       {
         id: 7,
         title:"Oraimo Watch 2R Bluetooth Calling Smart Watch for Men and Women,1.39 HD Smart Fitness Watch with Stepping Meter Heart Rate",
       image:"https://m.media-amazon.com/images/I/61shUuiQKiL._AC_UL320_.jpg",
       imageTwo:"	https://m.media-amazon.com/images/I/61FHscI4SAL._AC_SY450_.jpg",
       imageThree: "https://m.media-amazon.com/images/I/71xOGlDdD4L._AC_SY450_.jpg",
       imageFour:"https://m.media-amazon.com/images/I/71RzxAnoWjL._AC_SY450_.jpg",
         starNum: 74,
         para: "200+ bought in past month",
         price: 1.203,
         del: 1.300,
         otherpara: "Get it as soon as tomorrow, 24 Mar",
        otherparapara: "Fulfilled by Amazon - FREE Shipping",
        inStock: true,
        rating:5,
        reviews: "69,548",
        brandName:"Samsung",
        modelName:"G21",
        wirelessProvider:"Unlocked for All Carriers",
        OperatingSystem: "Android",
        cellular: "5G",
        memoryStorage:"256GB"
     }
   ]
   export default ElectronicsDatasThree