 const  ElectronicsDatasOne=[
    {
        id: 1,
        image: "https://m.media-amazon.com/images/I/317IeU7IATL._AC_SX450_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/317IeU7IATL._AC_SX450_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/218nnqhKXrL._AC_SX450_.jpg",
        imageFour:"https://m.media-amazon.com/images/I/41ugRZrc6WL._AC_SX450_.jpg",
        title: "LG UHD 4K TV 55 Inch UQ7500 Series, Cinema Screen Design 4K Active HDR WebOS Smart AI ThinQ - 55UQ75006L, Bluetooth, Wi-Fi, Ethernet, HDMI, NFC",
        starNum: 27,
        para: "200+ bought in past month",
        price: 19.999,
        del: 17.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/61ERH+yIyiL._AC_UL320_.jpg",
        imageTwo:"	https://m.media-amazon.com/images/I/61UpnjTTo8L._AC_SX679_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/41+dk8b4+OL._AC_SX679_.jpg",
        imageFour:"https://m.media-amazon.com/images/I/51QoWcfEdYL._AC_SX679_.jpg",
        title: "Samsung Galaxy A55 5G, Android Smartphone, Dual SIM Mobile Phone, 8GB RAM, 256GB Storage, Awesome Navy - 1 year Warranty",
        starNum: 7145,
        para: "200+ bought in past month",
        price:  18.999,
        del: 20.298,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
      id: 9,
      image: "	https://m.media-amazon.com/images/I/51Azws7WRIL._AC_UL320_.jpg",
      imageTwo:"	https://m.media-amazon.com/images/I/61UpnjTTo8L._AC_SX679_.jpg",
      imageThree:"https://m.media-amazon.com/images/I/41+dk8b4+OL._AC_SX679_.jpg",
      imageFour:"https://m.media-amazon.com/images/I/51QoWcfEdYL._AC_SX679_.jpg",
      title: "EZVIZ CS-TY1 1080p 360-Degree WiFi Smart Home Security Camera, Intelligent Surveillance Camera with Night Vision, Smart Tracking, Two-way",
      starNum: 7145,
      para: "200+ bought in past month",
      price:  1.029,
      del: 1.700,
      otherpara: "Get it as soon as tomorrow, 24 Mar",
     otherparapara: "Fulfilled by Amazon - FREE Shipping",
     inStock: true,
     rating:5,
     reviews: "69,548",
     brandName:"Nokia",
     modelName:"G21",
     wirelessProvider:"Unlocked for All Carriers",
     OperatingSystem: "Android",
     cellular: "5G",
     memoryStorage:"256GB"
  }
 
   ]
export default ElectronicsDatasOne

  