const  FashionResults=[
    {
        id: 1,
        image: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageTwo: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        price:1.830, 
        title: "Power Lock Travel Plug adapter Converter – gray and white",
        starNum: 74,
        para: "200+ bought in past month",
        del: 1.947,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        imageTwo: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        imageThree: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
  	    imageFour: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        title: "SHOWAY Portable Luggage Scale 50kg Electronic Digital Suitcase Travel Bag ...",
        starNum: 74,
        para: "200+ bought in past month",
        price: 175,
        del: 218,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 3,
        image: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageTwo: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        imageThree: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "Power Lock Travel Plug adapter Converter – gray and white",
        starNum: 74,
        para: "200+ bought in past month",
        price: 42,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 4,
        image: "https://m.media-amazon.com/images/I/719L205NrBL._AC_SX679_.jpg",
        imageTwo: "	https://m.media-amazon.com/images/I/718UyiI8ynL._AC_SX679_.jpg",
        imageThree: "https://m.media-amazon.com/images/I/719L205NrBL._AC_SX679_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/718UyiI8ynL._AC_SX679_.jpg",
        title: "Lubardy Laptop Backpack for Men and Women with 17.3inch Computer Compartment",
        starNum: 74,
        para: "200+ bought in past month",
        price: 234,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 5,
        image: "https://m.media-amazon.com/images/I/61ysYAyjoqL._AC_UL320_.jpg",
        imageTwo: "	https://m.media-amazon.com/images/I/41-HhkaCQUL._AC_SY500_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/41EsAaJUYgL._AC_SY500_.jpg",    
        imageFour: "https://m.media-amazon.com/images/I/41EsAaJUYgL._AC_SY500_.jpg",
        title: "Men Plain Wide Round Neck Sleeveless",
        starNum: 74,
        para: "200+ bought in past month",
        price: 386,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
        image: "	https://m.media-amazon.com/images/I/518BrG3bboL._AC_UL320_.jpg",
        imageTwo: " 	https://m.media-amazon.com/images/I/51N3BNecoqL._AC_SY500_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/51erTzmvkmL._AC_SY500_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "WaterProof Burkini One Piece Swimsuit For Women",
        starNum: 74,
        para: "200+ bought in past month",
        price: 725,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 7,
        image: "		https://m.media-amazon.com/images/I/51hQa75MPAL._AC_UL320_.jpg",
        imageTwo: " 	https://m.media-amazon.com/images/I/51RUGGASiiL._AC_SX569_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/51SF6tt0gnL._AC_SX569_.jpg",
        title: "Generic Liquid Adding Soft Fur Cleaning Brush, Multifunctional Shoe Brush with Liquid",
        starNum: 74,
        para: "200+ bought in past month",
        price: 25,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 8,
        image: "https://m.media-amazon.com/images/I/51bMcG93dbL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51bMcG93dbL._AC_UL320_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/51bMcG93dbL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/51bMcG93dbL._AC_UL320_.jpg",
        price:1.830,   
        title: "New York NY Baseball & Snapback Hat For Unisex",
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 9,
        image: "		https://m.media-amazon.com/images/I/811B10WlouL._AC_UL320_.jpg",
        imageTwo: " 	https://m.media-amazon.com/images/I/51N3BNecoqL._AC_SY500_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/51erTzmvkmL._AC_SY500_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "Waterproof Women's 2 Piece Tankini Swimsuit Top and Shorts 40",
        starNum: 74,
        para: "200+ bought in past month",
        price: 5.664,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default FashionResults




