 const FashionResultsTwo =[
    {
        id: 4,
        image: "https://m.media-amazon.com/images/I/719L205NrBL._AC_SX679_.jpg",
        imageTwo: "	https://m.media-amazon.com/images/I/718UyiI8ynL._AC_SX679_.jpg",
        imageThree: "https://m.media-amazon.com/images/I/719L205NrBL._AC_SX679_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/718UyiI8ynL._AC_SX679_.jpg",
        title: "Lubardy Laptop Backpack for Men and Women with 17.3inch Computer Compartment",
        starNum: 74,
        para: "200+ bought in past month",
        price: 234,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 5,
        image: "https://m.media-amazon.com/images/I/61ysYAyjoqL._AC_UL320_.jpg",
     imageTwo: "	https://m.media-amazon.com/images/I/41-HhkaCQUL._AC_SY500_.jpg",
    imageThree: "	https://m.media-amazon.com/images/I/41EsAaJUYgL._AC_SY500_.jpg",
        imageFour: "https://m.media-amazon.com/images/I/41EsAaJUYgL._AC_SY500_.jpg",
        title: "Men Plain Wide Round Neck Sleeveless",
        starNum: 74,
        para: "200+ bought in past month",
        price: 386,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
        image: "	https://m.media-amazon.com/images/I/518BrG3bboL._AC_UL320_.jpg",
  
        imageTwo: " 	https://m.media-amazon.com/images/I/51N3BNecoqL._AC_SY500_.jpg",
    imageThree: "	https://m.media-amazon.com/images/I/51erTzmvkmL._AC_SY500_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "Power Lock Travel Plug adapter Converter – gray and white",
        // title: "Waterproof Women's 2 Piece Tankini Swimsuit Top and Shorts 40",
        starNum: 74,
        para: "200+ bought in past month",
        price: 725,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
]
export default FashionResultsTwo