
 const FashionResultsThree =[
    {
        id: 7,
        image: "		https://m.media-amazon.com/images/I/51hQa75MPAL._AC_UL320_.jpg",
        imageTwo: " 	https://m.media-amazon.com/images/I/51RUGGASiiL._AC_SX569_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/51SF6tt0gnL._AC_SX569_.jpg",
        title: "Generic Liquid Adding Soft Fur Cleaning Brush, Multifunctional Shoe Brush with Liquid",
        starNum: 74,
        para: "200+ bought in past month",
        price: 25,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 8,
        image: "			https://m.media-amazon.com/images/I/51bMcG93dbL._AC_UL320_.jpg",  
        title: "New York NY Baseball & Snapback Hat For Unisex",
        starNum: 74,
        para: "200+ bought in past month",
        price: 84,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 9,
        image: "		https://m.media-amazon.com/images/I/811B10WlouL._AC_UL320_.jpg",
        imageTwo: " 	https://m.media-amazon.com/images/I/51N3BNecoqL._AC_SY500_.jpg",
        imageThree: "	https://m.media-amazon.com/images/I/51erTzmvkmL._AC_SY500_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "Waterproof Women's 2 Piece Tankini Swimsuit Top and Shorts 40",
        starNum: 74,
        para: "200+ bought in past month",
        price: 5.664,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default FashionResultsThree

