export const FashionResultsOne =[
    {
        id: 1,
        image: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageTwo: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        price:1.830, 
        title: "Power Lock Travel Plug adapter Converter – gray and white",
        starNum: 74,
        para: "200+ bought in past month",
        del: 1.947,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        imageTwo: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        imageThree: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
  	imageFour: "https://m.media-amazon.com/images/I/51BDfXXuUWL._AC_UL320_.jpg",
        title: "SHOWAY Portable Luggage Scale 50kg Electronic Digital Suitcase Travel Bag ...",
        starNum: 74,
        para: "200+ bought in past month",
        price: 175,
        del: 218,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 3,
        image: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageTwo: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
    imageThree: "https://m.media-amazon.com/images/I/61kgSw77MEL._AC_UL320_.jpg",
        imageFour: " https://m.media-amazon.com/images/I/51jhxP5-wSL._AC_SX466_.jpg",
        title: "Power Lock Travel Plug adapter Converter – gray and white",
        starNum: 74,
        para: "200+ bought in past month",
        price: 42,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default FashionResultsOne