const HouseholdAppliancesDatas = [
    {
        id: 1,
        title:"Tornado TSF-18XW Electric Tower Fans 3 Speeds - Black",
        image:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageTwo:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageThree:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageFour:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
	starNum: 74,
        para: "200+ bought in past month",
        price: 13.599,
        del: 16.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
        title:" LG Washing Machine, 8kg, Front Load- F2T2TYM1S.ADSPEEC ",
        image:" https://m.media-amazon.com/images/I/91U0fGLWfkL._AC_UL320_.jpg",
        imageTwo:"  	https://m.media-amazon.com/images/I/911JgmqjrhL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg ",
        imageFour:"  https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg",
        price:20.861,
	starNum: 74333,
        para: "200+ bought in past month",
        del: 4.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
 
    {
        id: 3,
        title:" Tefal Silence Force Stand Fan With Remote Control, 16 Inch, Black - ",
        image:" 	https://m.media-amazon.com/images/I/61uW6za+ckL._AC_UL320_.jpg",
        imageTwo:" https://m.media-amazon.com/images/I/61AzXZRaLmL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg ",
        imageFour:"https://m.media-amazon.com/images/I/51Cs2oFgjdL._AC_SX679_.jpg",
        price:2149,
	 starNum: 74,
        para: "200+ bought in past month",
        del: 4.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
    {
        id: 4,
        title:"Tornado Electric Blender 250 Watt 1.5 Liter 2 Mills White MX900/2 ",
        image:" https://m.media-amazon.com/images/I/511a259tjdL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51sSBYrTMOL._AC_SX569_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/31TJaQUD1wL._AC_.jpg" ,
        imageFour:" https://m.media-amazon.com/images/I/31TJaQUD1wL._AC_.jpg",
        price:1.100,    
	starNum: 74,
        para: "200+ bought in past month",
        del: 17.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
	
    {
        id: 5,
        title:"Philips Essential Air Fryer XL 1.2KG, 6.2L Capacity, Digital Screen,Black – International Warranty – HD9270/90",
        image:"	https://m.media-amazon.com/images/I/51Vuh0WBkqL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51cNbHPnLuL._AC_SX569_.jpg",
        imageThree:"	https://m.media-amazon.com/images/I/51m2+QMLqiL._AC_SX569_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61gcarLHNyL._AC_SX569_.jpg",
        price:6.940,  
	starNum: 74,
        para: "200+ bought in past month",
        del: 17.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },   
  
 {
        id: 6,
        title:"Fresh stand electric fan shabah 18 inch with remote, FSF18",
        image:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        starNum: 74,
        para: "200+ bought in past month",
        del: 17.599,
        price: 16.500,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 7,
        title:"Samsung refrigerator rt30a3000sa/mr 305l - metal graphite- (local warranty) ",
        image:" 	https://m.media-amazon.com/images/I/61KP1uVFxTL._AC_UL320_.jpg",
        imageTwo:"  	https://m.media-amazon.com/images/I/911JgmqjrhL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg ",
        imageFour:"  https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg",
        price:28.900,
	    starNum: 74333,
        para: "200+ bought in past month",
      
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 8,
        title:"TOSHIBA Kitchen Ventilating Fan 25 cm Oil Drawer Creamy VRH25J10C ",
        image:" https://m.media-amazon.com/images/I/51QnoxX+7QL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51sSBYrTMOL._AC_SX569_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/31TJaQUD1wL._AC_.jpg" ,
        imageFour:" https://m.media-amazon.com/images/I/31TJaQUD1wL._AC_.jpg",
        price:1.290,    
	starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 9,
        title:"Fresh Rafale Ceiling Fan 56 Inch - White",
        image:"	https://m.media-amazon.com/images/I/41QlmBgRXSL._AC_UL320_.jpg",
    
        imageTwo:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        price:1.232, 
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
	
]
export default HouseholdAppliancesDatas

