const HouseholdAppliancesDatasThree =[

    {
        id: 5,
        title:"Philips Essential Air Fryer XL 1.2KG, 6.2L Capacity, Digital Screen,Black – International Warranty – HD9270/90",
        image:"	https://m.media-amazon.com/images/I/51Vuh0WBkqL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/51cNbHPnLuL._AC_SX569_.jpg",
        imageThree:"	https://m.media-amazon.com/images/I/51m2+QMLqiL._AC_SX569_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61gcarLHNyL._AC_SX569_.jpg",
        price:6.940,  
	starNum: 74,
        para: "200+ bought in past month",
        del: 17.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },   
  
 {
        id: 6,
        title:"Fresh stand electric fan shabah 18 inch with remote, FSF18",
        image:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        price:1.830, 
        starNum: 74,
        para: "200+ bought in past month",
        del: 17.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 9,
        title:"Fresh Rafale Ceiling Fan 56 Inch - White",
        image:"	https://m.media-amazon.com/images/I/41QlmBgRXSL._AC_UL320_.jpg",
    
        imageTwo:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg" ,
        imageFour:"https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_UL320_.jpg",
        price:1.232, 
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default HouseholdAppliancesDatasThree