const HouseholdAppliancesDatasOne =[
    {
        id: 1,
        title:"Tornado TSF-18XW Electric Tower Fans 3 Speeds - Black",
        image:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageTwo:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageThree:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
        imageFour:"	https://m.media-amazon.com/images/I/61dAqTxKSUL._AC_SY879_.jpg",
	starNum: 74,
        para: "200+ bought in past month",
        price: 13.599,
        del: 16.599,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
        title:" LG Washing Machine, 8kg, Front Load- F2T2TYM1S.ADSPEEC ",
        image:" https://m.media-amazon.com/images/I/91U0fGLWfkL._AC_UL320_.jpg",
        imageTwo:"  	https://m.media-amazon.com/images/I/911JgmqjrhL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg ",
        imageFour:"  https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg",
        price:20.861,
	starNum: 74333,
        para: "200+ bought in past month",
        del: 4.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 7,
        title:"Samsung refrigerator rt30a3000sa/mr 305l - metal graphite- (local warranty) ",
        image:" 	https://m.media-amazon.com/images/I/61KP1uVFxTL._AC_UL320_.jpg",
        imageTwo:"  	https://m.media-amazon.com/images/I/911JgmqjrhL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg ",
        imageFour:"  https://m.media-amazon.com/images/I/91SiN4+UA+L._AC_SX679_.jpg",
        price:28.900,
	    starNum: 74333,
        para: "200+ bought in past month",
      
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default HouseholdAppliancesDatasOne