const PhonesDatasOne =[
    {
        id: 1,
        image: "	https://m.media-amazon.com/images/I/61ERH+yIyiL._AC_UL320_.jpg",
	imageTwo:" 	https://m.media-amazon.com/images/I/61UpnjTTo8L._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/41TLwEyPz9L._AC_SX679_.jpg ",
	imageFour:"	https://m.media-amazon.com/images/I/51QoWcfEdYL._AC_SX679_.jpg ",
        title: "Samsung Galaxy A55 5G, Android Smartphone, Dual SIM Mobile Phone, 8GB RAM, 256GB Storage, Awesome Navy - 1 year Warranty",
        starNum: 74,
        para: "200+ bought in past month",
        price: 18.599,
	    del:23.500,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
         image: "	https://m.media-amazon.com/images/I/71ve-OMxzyL._AC_UL320_.jpg",
	imageTwo:" 		https://m.media-amazon.com/images/I/61tQWqZBmZL._AC_SX679_.jpg",
	imageThree:"https://m.media-amazon.com/images/I/618Y9pzx2FL._AC_SX679_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61V1zVpOliL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 128GB Storage, Light Green",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.699,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 7,
      image: "https://m.media-amazon.com/images/I/81FmX+ooJQL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/81FmX+ooJQL._AC_SX569_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/7116PnJIqEL._AC_SX522_.jpg",
	imageFour:"	https://m.media-amazon.com/images/I/61GfugF7lbL._AC_SX450_.jpg",
        title: "HONOR X9b 5G 12GB+256GB Sunrise Orange Dual Card",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.999,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  
]
export default PhonesDatasOne