const PhonesDatasThree = [
    {
        id: 5,
      image: "https://m.media-amazon.com/images/I/61jBR+KUEDL._AC_SX679_.jpg",
	imageTwo:"https://m.media-amazon.com/images/I/6165AEJCq9L._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61Ynshha-2L._AC_SX679_.jpg",
	imageFour:"https://m.media-amazon.com/images/I/51oXUOOpPOL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 6GB RAM, 128GB Storage, Black",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 5.899,
       
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
      image: "https://m.media-amazon.com/images/I/71-QzvIZnVL._AC_SX450_.jpg",
	imageTwo:"https://m.media-amazon.com/images/I/61b6kzfrtUL._AC_SX450_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61is3RFobIL._AC_SX450_.jpg",
	imageFour:"	https://m.media-amazon.com/images/I/61GfugF7lbL._AC_SX450_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 128GB Storage,Silver",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.999,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  
     {
        id: 9,
      image: "https://m.media-amazon.com/images/I/91mfZjs+BiL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/917WGqwq5sL._AC_SY450_.jpg",
	imageThree:"		https://m.media-amazon.com/images/I/71FGL-1TzPL._AC_SY450_.jpg",
	imageFour:"			https://m.media-amazon.com/images/I/71FGL-1TzPL._AC_SY450_.jpg",
        title: "Realme C53 Dual-SIM 256GB ROM + 8GB RAM 4G (Mighty Black) - Middle East Version",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 7.299,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default PhonesDatasThree