const PhonesDatasTwo = [
    {
        id: 3,
         image: "	https://m.media-amazon.com/images/I/71ve-OMxzyL._AC_UL320_.jpg",
	imageTwo:" 		https://m.media-amazon.com/images/I/61V469PlvML._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61V469PlvML._AC_SX679_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61EyJjwKFiL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 64GB Storage, Black",
      
        starNum: 74333,
        para: "200+ bought in past month",
        price:4.500,
        del: 6.220,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 4,
         image: "		https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
	imageTwo:" 			https://m.media-amazon.com/images/I/51H24V4z3jL._AC_SX569_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/71Lv32ogyOL._AC_SX569_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
        title: "Samsung Galaxy S23 FE 5G Dual SIM Android Smartphone, 8GB RAM, 256GB ROM - Cream",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 22.999,
      
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 8,
      image: "https://m.media-amazon.com/images/I/51xTkm8N0fL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/41Vubc-zzoL._AC_SY606_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/413NLkp836L._AC_SY606_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/41TVJSbbjUL._AC_SY606_.jpg",
        title: "Redmi Note 13 (Midnight Black 8GB RAM, 256 Storage) - Super-clear 108MP triple camera |120Hz FHD+AMOLED display | Immersive viewing with ultra-",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 9.143,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default PhonesDatasTwo