const PhonesDatas = [
    {
        id: 1,
        image: "	https://m.media-amazon.com/images/I/61ERH+yIyiL._AC_UL320_.jpg",
	imageTwo:" 	https://m.media-amazon.com/images/I/61UpnjTTo8L._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/41TLwEyPz9L._AC_SX679_.jpg ",
	imageFour:"	https://m.media-amazon.com/images/I/51QoWcfEdYL._AC_SX679_.jpg ",
        title: "Samsung Galaxy A55 5G, Android Smartphone, Dual SIM Mobile Phone, 8GB RAM, 256GB Storage, Awesome Navy - 1 year Warranty",
        starNum: 74,
        para: "200+ bought in past month",
        price: 18.599,
	del:23.500,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
         image: "	https://m.media-amazon.com/images/I/71ve-OMxzyL._AC_UL320_.jpg",
	imageTwo:" 		https://m.media-amazon.com/images/I/61tQWqZBmZL._AC_SX679_.jpg",
	imageThree:"https://m.media-amazon.com/images/I/618Y9pzx2FL._AC_SX679_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61V1zVpOliL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 128GB Storage, Light Green",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.699,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 3,
         image: "	https://m.media-amazon.com/images/I/71ve-OMxzyL._AC_UL320_.jpg",
	imageTwo:" 		https://m.media-amazon.com/images/I/61V469PlvML._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61V469PlvML._AC_SX679_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61EyJjwKFiL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 64GB Storage, Black",
      
        starNum: 74333,
        para: "200+ bought in past month",
        price:4.500,
        del: 6.220,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 4,
         image: "		https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
	imageTwo:" 			https://m.media-amazon.com/images/I/51H24V4z3jL._AC_SX569_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/71Lv32ogyOL._AC_SX569_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/61H2nUIKiNL._AC_SX569_.jpg",
        title: "Samsung Galaxy S23 FE 5G Dual SIM Android Smartphone, 8GB RAM, 256GB ROM - Cream",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 22.999,
      
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 5,
      image: "https://m.media-amazon.com/images/I/61jBR+KUEDL._AC_SX679_.jpg",
	imageTwo:"https://m.media-amazon.com/images/I/6165AEJCq9L._AC_SX679_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61Ynshha-2L._AC_SX679_.jpg",
	imageFour:"https://m.media-amazon.com/images/I/51oXUOOpPOL._AC_SX679_.jpg",
        title: "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 6GB RAM, 128GB Storage, Black",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 5.899,
       
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
      image: "https://m.media-amazon.com/images/I/71-QzvIZnVL._AC_SX450_.jpg",
	imageTwo:"https://m.media-amazon.com/images/I/61b6kzfrtUL._AC_SX450_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/61is3RFobIL._AC_SX450_.jpg",
	imageFour:"	https://m.media-amazon.com/images/I/61GfugF7lbL._AC_SX450_.jpg",
        title: "Samsung Galaxy A05 LTE, Android Smartphone, Dual SIM Mobile Phone, 4GB RAM, 128GB Storage,Silver",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.999,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  
    {
        id: 7,
      image: "https://m.media-amazon.com/images/I/81FmX+ooJQL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/81FmX+ooJQL._AC_SX569_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/7116PnJIqEL._AC_SX522_.jpg",
	imageFour:"	https://m.media-amazon.com/images/I/61GfugF7lbL._AC_SX450_.jpg",
        title: "HONOR X9b 5G 12GB+256GB Sunrise Orange Dual Card",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 4.999,
        del: 6.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  
    {
        id: 8,
      image: "https://m.media-amazon.com/images/I/51xTkm8N0fL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/41Vubc-zzoL._AC_SY606_.jpg",
	imageThree:"	https://m.media-amazon.com/images/I/413NLkp836L._AC_SY606_.jpg",
	imageFour:"		https://m.media-amazon.com/images/I/41TVJSbbjUL._AC_SY606_.jpg",
        title: "Redmi Note 13 (Midnight Black 8GB RAM, 256 Storage) - Super-clear 108MP triple camera |120Hz FHD+AMOLED display | Immersive viewing with ultra-",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 9.143,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  
    {
        id: 9,
      image: "https://m.media-amazon.com/images/I/91mfZjs+BiL._AC_UL320_.jpg",
	imageTwo:"	https://m.media-amazon.com/images/I/917WGqwq5sL._AC_SY450_.jpg",
	imageThree:"		https://m.media-amazon.com/images/I/71FGL-1TzPL._AC_SY450_.jpg",
	imageFour:"			https://m.media-amazon.com/images/I/71FGL-1TzPL._AC_SY450_.jpg",
        title: "Realme C53 Dual-SIM 256GB ROM + 8GB RAM 4G (Mighty Black) - Middle East Version",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 7.299,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default PhonesDatas
