
const productsparts = [
    {
        id: 1,
        image: "	https://m.media-amazon.com/images/I/71xU8w3fHJL._AC_UL320_.jpg",
        title: "Samsung Galaxy A54 Dual SIM 8GB Ram+128GB ROM (6.23 Inches) (5G) - (Awesome Graphite)",
        starNum: 74,
        para: "200+ bought in past month",
        price: 13.599,
        del: 16.947,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
  
 
    {
        id: 2,
        image: "https://m.media-amazon.com/images/I/71AQ3qEZ-VL._AC_UL320_.jpg",
        title: "Nokia G21 Dual SIM 4GB Ram+128GB ROM (6.5 Inches) (4G) - (Dusk)",
        starNum: 74333,
        para: "200+ bought in past month",
        price: 3.999,
        del: 4.999,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Nokia",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
 
   

    {
        id: 3,
        image: "https://m.media-amazon.com/images/I/61jBR+KUEDL._AC_UL320_.jpg",
        title: "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 4GB RAM",
        starNum: 74,
        para: "200+ bought in past month",
        price: 6.333,
        del: 7.333,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: false,
       rating:3,
       reviews: "69,548",
       brandName:"Samsung",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },    
       {
        id: 4,
        image: "https://m.media-amazon.com/images/I/61jBR+KUEDL._AC_UL320_.jpg",
        title: "Samsung Galaxy A05s, Android Smartphone, Dual SIM Mobile Phone, LTE, 6GB RAM",
        starNum: 74,
        para: "200+ bought in past month",
        price: 7.444,
        del: 8.444,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:4,
       reviews: "69,548",
       brandName:"Samsung",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },  


 {
        id: 5,
        image: "	https://m.media-amazon.com/images/I/51kQgMblg9L._AC_UL320_.jpg",
        title: "Samsung Galaxy A54 - Dual SIM Mobile Phone Android, 8GB RAM, 128GB, 5G, Awesome Lime",
        starNum: 74,
        para: "200+ bought in past month",
        price: 13.500,
        del: 816.500,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: false,
       rating:5,
       reviews: "69,548",
       brandName:"Samsung",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
       {
        id: 6,
        image: "https://m.media-amazon.com/images/I/719HV2e6-sL._AC_UL320_.jpg",
        title: "SAMSUNG Galaxy S24 Ultra, AI Android Smartphone, 256GB Storage, 12GB RAM, 200MP Camera, S Pen, Long Battery Life",
        starNum: 74,
        para: "200+ bought in past month",
        price: 56.400,
        del: 85.400,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       brandName:"Samsung",
       modelName:"G21",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default productsparts