const VideoGamesDatasTwo = [
    {
        id: 4,
        title:" EFISH World Blue Gaming Mouse Pad 30 x 80cm",
        image:"	https://m.media-amazon.com/images/I/61zUwGDRO4L._AC_SX569_.jpg ",
        imageTwo:" 	https://m.media-amazon.com/images/I/71FOJg7Gt3L._AC_SX569_.jpg",
        imageThree: " 	https://m.media-amazon.com/images/I/71lruVYGHzL._AC_SX569_.jpg",
        imagrFour:" https://m.media-amazon.com/images/I/81+FhUJQnKL._AC_SX569_.jpg",
        price: " 700",        
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 5,
        title:" 505 Games Control Video Game for PS4 Games Control Video Game ",
        image:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageTwo:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageThree:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageFour:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        price: 1999 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
        title:"PS4 Controller, USB - PS4 DualShock 4 Wireless Controller - Black",
        image:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageTwo:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageFour:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        price:  690,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default VideoGamesDatasTwo