const VideoGamesDatasOne = [
    {
        id: 1,
        title:" Gaming Headset PS4 Headset with 7.1 Surround Sound, Xbox One Headset with Noise Cancelling",
        image:"https://m.media-amazon.com/images/I/41aj9LfEr4L._AC_US40_.jpg ",
        imageFour: " https://m.media-amazon.com/images/I/51wqe+O7-6L._AC_US40_.jpg",
        imageTwo:" https://m.media-amazon.com/images/I/71eqk8gfAsL._AC_SY450_.jpg",
        imageThree:":	https://m.media-amazon.com/images/I/71sZKGYAaYL._AC_SY450_.jpg ",
        price: 499,  
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 2,
        title:"  Banhey Rearview Mirror Phone Holder for Car-Upgraded ",
        image:" https://m.media-amazon.com/images/I/41csTAw0+nL._AC_SR38,50_.jpg",
        imgeFour:" https://m.media-amazon.com/images/I/51qS+H0NXGL._AC_SR38,50_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/41B9xfk0zrL._AC_SR38,50_.jpg ",
        imageThree:"https://m.media-amazon.com/images/I/51w12hbUi0L._AC_SR38,50_.jpg ",
        price: 90, 
	    starNum: 74,
        para: "200+ bought in past month",
        del: 100,
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 3,
        title:" YAEYE Wired Controller for Xbox 360, Game Controller for 360 with Dual-Vibration",
        image:"https://m.media-amazon.com/images/I/71r1LDErYwS._AC_UL320_.jpg ",
        imageFour: " https://m.media-amazon.com/images/I/41CGNHHGIcL._AC_SR38,50_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/41ZHBKL-E5S._AC_SR38,50_.jpg ",
        imageThree: "https://m.media-amazon.com/images/I/51LA1yXF9tS._AC_SR38,50_.jpg ",
        price: 400,    
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default VideoGamesDatasOne