
const VideoGamesDatas = [
    {
        id: 1,
        title:" Gaming Headset PS4 Headset with 7.1 Surround Sound, Xbox One Headset with Noise Cancelling",
        image:"https://m.media-amazon.com/images/I/41aj9LfEr4L._AC_US40_.jpg ",
        imageFour: " https://m.media-amazon.com/images/I/51wqe+O7-6L._AC_US40_.jpg",
        imageTwo:" https://m.media-amazon.com/images/I/71eqk8gfAsL._AC_SY450_.jpg",
        imageThree:"	https://m.media-amazon.com/images/I/71sZKGYAaYL._AC_SY450_.jpg ",
        price: 499,  
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 2,
        title:" Banhey Rearview Mirror Phone Holder for Car-Upgraded ",
        image:" https://m.media-amazon.com/images/I/41csTAw0+nL._AC_SR38,50_.jpg",
        imgeFour:" https://m.media-amazon.com/images/I/51qS+H0NXGL._AC_SR38,50_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/41B9xfk0zrL._AC_SR38,50_.jpg ",
        imageThree:"https://m.media-amazon.com/images/I/51w12hbUi0L._AC_SR38,50_.jpg ",
        price: 90, 
	    starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 3,
        title:" YAEYE Wired Controller for Xbox 360, Game Controller for 360 with Dual-Vibration",
        image:"https://m.media-amazon.com/images/I/71r1LDErYwS._AC_UL320_.jpg ",
        imageFour: " https://m.media-amazon.com/images/I/41CGNHHGIcL._AC_SR38,50_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/41ZHBKL-E5S._AC_SR38,50_.jpg ",
        imageThree: "https://m.media-amazon.com/images/I/51LA1yXF9tS._AC_SR38,50_.jpg ",
        price: 400,    
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 4,
        title:" EFISH World Blue Gaming Mouse Pad 30 x 80cm",
        image:"	https://m.media-amazon.com/images/I/61zUwGDRO4L._AC_SX569_.jpg ",
        imageTwo:" 	https://m.media-amazon.com/images/I/71FOJg7Gt3L._AC_SX569_.jpg",
        imageThree: " 	https://m.media-amazon.com/images/I/71lruVYGHzL._AC_SX569_.jpg",
        imagrFour:" https://m.media-amazon.com/images/I/81+FhUJQnKL._AC_SX569_.jpg",
        price: " 700",        
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 5,
        title:" 505 Games Control Video Game for PS4 Games Control Video Game ",
        image:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageTwo:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageThree:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        imageFour:"	https://m.media-amazon.com/images/I/71An6kFALOL._AC_SX385_.jpg ",
        price: 1999 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    },
    {
        id: 6,
        title:"PS4 Controller, USB - PS4 DualShock 4 Wireless Controller - Black",
        image:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageTwo:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageThree:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        imageFour:" https://m.media-amazon.com/images/I/6167bRo3wGL._AC_SX679_.jpg",
        price:  690,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 7,
        title:" NexiGo Vertical Stand with Cooling Fan and Game Storage for PS5 Disc & Digital Editions",
        image:"https://m.media-amazon.com/images/I/61g2AaP+tGL._AC_SX466_.jpg ",
        imageTwo:"	https://m.media-amazon.com/images/I/81SivXULX-L._AC_SX466_.jpg ",
        imageThree:" 	https://m.media-amazon.com/images/I/7124UMX9sPL._AC_SX466_.jpg",
        imageFour:"	https://m.media-amazon.com/images/I/7124UMX9sPL._AC_SX466_.jpg ",
        price: 799,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 8,
        title:" Odaban F2 RGB Gaming Headset 7.1 Surround Sound",
        image:"	https://m.media-amazon.com/images/I/71od4dD13lL._AC_SX466_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/81AyvdvgZ1L._AC_SY450_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/81eRuKXfwsL._AC_SY450_.jpg ",
        imageFour:"https://m.media-amazon.com/images/I/71SM57t-HdL._AC_SY450_.jpg",
        price: 448 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 9,
        title:" Silicone Rubber Cover Anti-Slip Skin for Playstation 5 Controller Grips,Protective Case for PS5 Wireless",
        image:" https://m.media-amazon.com/images/I/61mGr8Z+zRS._AC_SX569_.jpg",
        imageTwo:"	https://m.media-amazon.com/images/I/617TkHNTNIS._AC_SX569_.jpg ",
        imageThree:"	https://m.media-amazon.com/images/I/51ikO5lEZ9S._AC_SX569_.jpg ",
        imageFour:"	https://m.media-amazon.com/images/I/61g9G1c9F7S._AC_SX569_.jpg ",
        price: 150 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]


export default VideoGamesDatas


 

   







                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    