const VideoGamesDatasThree =[
    {
        id: 7,
        title:" NexiGo Vertical Stand with Cooling Fan and Game Storage for PS5 Disc & Digital Editions",
        image:"https://m.media-amazon.com/images/I/61g2AaP+tGL._AC_SX466_.jpg ",
        imageTwo:"	https://m.media-amazon.com/images/I/81SivXULX-L._AC_SX466_.jpg ",
        imageThree:" 	https://m.media-amazon.com/images/I/7124UMX9sPL._AC_SX466_.jpg",
        imageFour:"	https://m.media-amazon.com/images/I/7124UMX9sPL._AC_SX466_.jpg ",
        price: 799,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 8,
        title:" Odaban F2 RGB Gaming Headset 7.1 Surround Sound, Mic & LED Light Noise Cancelling Microphone Over Ear MULTI-PLATFORM COMPATIBLE",
        image:"	https://m.media-amazon.com/images/I/71od4dD13lL._AC_SX466_.jpg",
        imageTwo:"https://m.media-amazon.com/images/I/81AyvdvgZ1L._AC_SY450_.jpg",
        imageThree:"https://m.media-amazon.com/images/I/81eRuKXfwsL._AC_SY450_.jpg ",
        imageFour:"https://m.media-amazon.com/images/I/71SM57t-HdL._AC_SY450_.jpg",
        price: 448 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }, 
    {
        id: 9,
        title:" Silicone Rubber Cover Anti-Slip Skin for Playstation 5 Controller Grips,Protective Case for PS5 Wireless",
        image:" https://m.media-amazon.com/images/I/61mGr8Z+zRS._AC_SX569_.jpg",
        imageTwo:"	https://m.media-amazon.com/images/I/617TkHNTNIS._AC_SX569_.jpg ",
        imageThree:"	https://m.media-amazon.com/images/I/51ikO5lEZ9S._AC_SX569_.jpg ",
        imageFour:"	https://m.media-amazon.com/images/I/61g9G1c9F7S._AC_SX569_.jpg ",
        price: 150 ,
        starNum: 74,
        para: "200+ bought in past month",
        otherpara: "Get it as soon as tomorrow, 24 Mar",
       otherparapara: "Fulfilled by Amazon - FREE Shipping",
       inStock: true,
       rating:5,
       reviews: "69,548",
       listOne: "BODY Dimensions: 158.2 x 76.7 x 8.2 mm (6.23 x 3.02 x 0.32 in)",
       listTwo: "DISPLAY Type: Super AMOLED, 120Hz, HDR10+, 1000 nits (HBM)",
       listThree: "PLATFORM OS: Android 13, One UI 5.1",
       listFour: "BATTERY Type: Li-Po 5000 mAh, non-removable",
       brandName:"Samsung",
       modelName:"Galaxy S24 Ultra",
       wirelessProvider:"Unlocked for All Carriers",
       OperatingSystem: "Android",
       cellular: "5G",
       memoryStorage:"256GB"
    }
]
export default VideoGamesDatasThree